# Generated by Django 5.2.3 on 2025-06-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('date_creation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_budget_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.prestataire')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordonnancement', models.DateField()),
                ('montant_ordonnancement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.lignebudgetaire')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant_regler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.lignebudgetaire')),
            ],
        ),
        migrations.CreateModel(
            name='RIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(max_length=24, unique=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ribs', to='budget_app.prestataire')),
            ],
        ),
    ]
