# Generated by Django 5.2.3 on 2025-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_ordonnancement_justificatifs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
