# Generated by Django 5.2.3 on 2025-06-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_reglement_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='compte_debite',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
