# Generated by Django 5.2.3 on 2025-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_reglement_compte_debite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeLocalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
