# Generated by Django 5.2.3 on 2025-06-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_codebanque_codelocalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='reglement_rel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
