# Generated by Django 5.2.3 on 2025-07-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_reglement_reglement_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='ordonnancement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.ordonnancement'),
        ),
    ]
