# Generated by Django 5.2.3 on 2025-07-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_reglement_ordonnancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebanque',
            name='nom_banque',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
