# Generated by Django 5.2.3 on 2025-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0009_codebanque_nom_banque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
