# Generated by Django 5.2.3 on 2025-07-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0010_alter_prestataire_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebudgetaire',
            name='rubrique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lignebudgetaire',
            name='sous_rubrique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
