# Generated by Django 5.2.3 on 2025-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0011_lignebudgetaire_rubrique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnancement',
            name='mode_paiement',
        ),
        migrations.AddField(
            model_name='reglement',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement'), ('cheque', 'Chèque'), ('espece', 'Espèce')], default='virement', max_length=10),
        ),
    ]
