# Generated by Django 5.2.3 on 2025-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0012_remove_ordonnancement_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='ref_cheque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
