# Generated by Django 5.2.3 on 2025-07-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0013_reglement_ref_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='compte_debite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
